// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pets

import (
	"database/sql"
)

type Category struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
}

type Pet struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	PhotoUrl sql.NullString `json:"photo_url"`
	Status   string         `json:"status"`
	Category sql.NullInt32  `json:"category"`
}

type PetTag struct {
	PetID int32 `json:"pet_id"`
	TagID int32 `json:"tag_id"`
}

type Tag struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}
